#!/usr/bin/dh-exec
debian/spampd.paranoid.logcheck => /etc/logcheck/ignore.d.paranoid/spampd
debian/spampd.server.logcheck   => /etc/logcheck/ignore.d.server/spampd
debian/spampd.sa-update-hook	=> /etc/spamassassin/sa-update-hooks.d/spampd
debian/process_arguments.sh	=> /usr/share/spampd/process_arguments.sh
debian/spampd.conf		=> /etc/spampd.conf

spampd.pl			=> /usr/sbin/spampd
spampd.8.gz			=> /usr/share/man/man8/spampd.8.gz

