#!/bin/sh -e

function handle_init_errs ()
{
	RET=$?
	if [ "$RET" = "6" ]; then
		return 0
	else
		exit $RET
	fi
	set -e
}

case "$1" in 
	configure|install|upgrade)
		adduser --system --group \
		        --no-create-home --home /nonexistent \
			--quiet spampd 
		dpkg-statoverride --add spampd spampd 775 /var/cache/spampd
		dpkg-statoverride --add root spampd 640 /etc/spampd.conf
		;;
	*)
		;;
esac

#DEBHELPER#
